name: Deweb uploader

on:
  push:
    branches: [main]

jobs:
  deweb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add buildnet
        network: [mainnet]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: Install
        run: npm ci
        working-directory: front

      - name: Build
        run: npm run build
        working-directory: front

      - name: Deploy to Massa DeWeb (${{ matrix.network }})
        id: deploy
        uses: massalabs/deweb-gh-action@v0.1.0
        with:
          config_file: ./front/deweb_cli_config.${{ matrix.network }}.json
          source_folder: ./front/dist
        env:
          # TODO: add buildnet key
          MASSA_DEWEB_SECRET_KEY: ${{ secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: Get deployed website address
        run: |
          echo "Deployed buildnet website address: ${{ steps.deploy.outputs.deployed-website }}"
